import { Stack } from "./stack.js";
import { Hole } from "./hole.js";
import * as __ from "./__/index.js";
export { Stack, Hole, __ };
export declare function ismain(meta: ImportMeta): boolean;
export declare function source(meta: ImportMeta): string;
export declare function sourcedir(meta: ImportMeta): string;
export declare function sleep(ms: number): Promise<void>;
export declare function UniqueId(v: object): BigInt;
