import "./globals/index.js";
import { Stack } from "./stack.js";
import { Delegate } from "./delegate.js";
import * as __ from "./__/index.js";
export { Stack, Delegate, __ };
export declare function ismain(meta: ImportMeta): boolean;
export declare function source(meta: ImportMeta): string;
export declare function sourcedir(meta: ImportMeta): string;
export declare function projectroot(meta: ImportMeta): Promise<string>;
export declare function sleep<T>(ms: number, v?: T): Promise<T | undefined>;
export declare function UniqueId(v: object): BigInt;
